lindlymatt/nevernote-q2

- knexfile.js
- migrations/01_users.js
- migrations/02_notes.js
- migrations/03_folders.js
- migrations/04_usersNotes.js
- migrations/05_noteTags.js
- migrations/06_folderNotes.js
- seeds/01_users.js
- seeds/02_notes.js
- seeds/03_folders.js
- seeds/04_noteTags.js
- seeds/05_userNotes.js
- seeds/06_folderNotes.js
Completed migrations and seed data for all 6 databases, with proper prefixes on the migrations and the seeds to accommodate reliance on other relations & data.
> Finished migrations and seeds data.

- migrations/01_users.js
- migrations/03_folders.js
- migrations/04_usersNotes.js
- migrations/05_noteTags.js
- migrations/06_folderNotes.js
- package.json
- seeds/01_users.js
- seeds/03_folders.js
- seeds/04_noteTags.js
- seeds/05_userNotes.js
- seeds/06_folderNotes.js
Changed all of the camelCase names to snake_case names to work properly in the SQL terminal formatting on pSQL.
> Changed migrations and seeds.

- routes/users.js
Added the users route for the requests concerning the users database. Made it RESTful with GET, GET :id, POST, PATCH :id and DELETE :id.
> Users route

- validations/users.js
Added users express validations for get, post, patch, and delete
> Express users validations

- validations/notes.js
Added validation for get, post, patch, and delete routes for notes
> Express notes validations

- routes/tokens.js
- server.js
Added token support in the /routes/token.js file, as well as added middleware to handle incoming requests with or without a token. Using the middleware to add user id in all requests.
> Authentication

- validations/folders.js
Add validations for get, post, patch, and delete routers for folders
> Express folder validations

- public/js/sidebar.js
Cleaned up sidebar.js folder and note creation looping by separating functions and added documentation for the functions
> Sidebar functionality

- package.json
- routes/tokens.js
- server.js
Corrected usage of `bcrypt` to use `brcypt-as-promised`, modified the router middleware so that the `/token` route can be accessed without having a token, and added `dotenv` to the npm package
> Post token

- routes/folders.js
- routes/tokens.js
- server.js
- validations/folders.js
- validations/tokens.js
Add in validations to ensure that the data going into the database is good
> Express validations

- routes/folders.js
- routes/notes.js
- routes/users.js
- validations/folders.js
- validations/notes.js
Added patch and delete route for notes and converted existing routes to use camelcase
> Route updates

- routes/users.js
Can update firstname and email without sending in a password
> Add ability to update user info other than password

- public/css/styles.css
- public/html/app.html
Made the pop-up modals more responsive so they work better.
> Modal's are responsive.

- routes/tokens.js
Added a direct login to the app page, from authentication on the landing page.
> Added direct login route to the designated place.

- public/html/app.html
- public/js/script.js
Made master branch stable with the iframe, GET requests on the workspace, and more.
> Bug fixing

- public/html/app.html
- public/js/cookies.js
- public/js/logout.js
- routes/tokens.js
Add a cookie to store the user's name and email in order to display it on the app page
> App updates

- public/js/script.js
> Super bug fixing

- routes/notes.js
Given an id, it will pull up the file at the id and send it to the browser to download
> Added route for downloading note at given id

- public/js/new_note.js
- public/js/script.js
- public/js/sidebarDiv.js
- routes/folders.js
- routes/notes.js
Edit and delete functionality fully alters the database.
> Edit and delete functionality works now.

- public/index.html
> Fixed landing page.

- public/js/script.js
Fixed iframe hiding on delete. You shouldn't see the note's content.
> Fixed iframe display issues.

- public/js/script.js
Add basic client-side folder moving with closed folders
> Drag and drop

- routes/users.js
- server.js
Rearranges authentication in order to allow users to signup
> Add redirect for the signup to go to app.html
